name = "mechcloud-oidc-proxy"
compatibility_date = "2024-06-03"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = "./dist"

[vars]
OAUTH2_PROXY_HOST = "https://portal-auth-proxy.mechcloud.io"

[[kv_namespaces]]
binding = "ACCOUNTS"
id = ""

[[r2_buckets]]
binding = ""
bucket_name = ""