name = "mechcloud-oidc-proxy"
compatibility_date = "2024-06-03"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = "./dist"

[vars]
OAUTH2_PROXY_HOST = "https://portal-auth-proxy.mechcloud.io"

[[kv_namespaces]]
binding = "HOSTS"
id = "179ac79e07a04b088a6d183cee2e3c14"

[[r2_buckets]]
binding = "APP1-DEV"
bucket_name = "app1-dev"

[[r2_buckets]]
binding = "APP1"
bucket_name = "app1"

[[r2_buckets]]
binding = "DEMO-STATIC1"
bucket_name = "demo-static1"



